version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: oxmldocgen-api
    build:
      context: ./oxmldocgen-api
      dockerfile: Dockerfile
    hostname: oxmldocgen-api
    restart: always
    logging: *default-logging